### PR TITLE
Add official support for Django 5.0

### PR DESCRIPTION
**Pull request by washeck**

### CODE REVIEW

**Review by alorence — APPROVED** [review]
Thank you for your contribution. Everything seems perfectly fine to me !

**Comment by alorence** [comment]
> I also suggest to drop support of EOLed Python/Django versions to reduce the testing matrix. If you agree, I can make a second PR to do that.

I will perform some cleanup soon. The README is not up-to-date with the current official Python / Django support matrix.

In this project, I try to ensure a good compatibility with older Python & Django versions. But you are right, it is probably a good time to drop support for some very old revisions.

I will drop support for a few version quickly, and will drop more in the next major release

**Comment by alorence** [comment]
@washeck a new release has just been published, with your latest contributions

**Comment by washeck** [comment]
Thanks :)

**Pull request merged**
